### ISSUE TITLE
doesn't work for 3.3?

### ISSUE THREAD

**Issue by Moistcrafter** [NotThorny/AttackModifier#10]
uh it doesnt seem to work for version 3.3

**Comment by NotThorny** [comment]
Since there is not yet an "official" grasscutter version supporting 3.3, I'll have to wait for that to check what needs to be fixed to make the plugin compatible. This is just to ensure I don't end up needing to update twice in the case that the official update is different from what is currently available, or if the official update ends up compatible and not needing any changes to the plugin to work.

**Comment by NotThorny** [comment]
Fixed as of release 1.1.
