### ISSUE TITLE
Why is there no effect after I enter the command

### ISSUE THREAD

**Issue by qwefghjml** [NotThorny/AttackModifier#18]
After I enter the command, the skill does not change at all

**Comment by NotThorny** [comment]
First make sure you're using the latest AttackModifier on latest Grasscutter. If you're doing so, then try with other gadgets. Not every gadget works, or is easily visible. I'd suggest you first swap to Raiden and use the default attacks provided with her to ensure the plugin is working as intended. This means you don't change anything with her, just use normal attacks and see.

Once you've confirmed the plugin is working fine, then you can get to testing gadgets out. You will have to test and try different ones because again, not all gadgets work in spawning, and some spawn but aren't easy to see or go straight down and may appear to have not done anything.
