### ISSUE TITLE
request for nilou

### ISSUE THREAD

**Issue by alyssio** [NotThorny/AttackModifier#4]
i want nilous normal atk to be childes (boss) arrow hydro shots i want her e to be the waves from the arrow whenever she attacks w the e and her burst to be childe slamming his electro polearm into the ground with a impact

**Comment by NotThorny** [comment]
This is probably the best you're going to get from my testing. I did change the code in the last request you made so that it's much easier to edit yourself, for reference. 
You just need the id of the gadget you want to spawn instead of needing the skill id and gadget id, so you can peruse the gadget excel config for what you want then just replace in the case for the attack you want to add it to.
[AttackModifier.zip](https://github.com/NotThorny/AttackModifier/files/9781935/AttackModifier.zip)

**Comment by alyssio** [comment]
how do i get gadget ids
